# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20190221_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commented',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commenter',
        ),
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='first_app.User'),
            preserve_default=False,
        ),
    ]
