# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-18 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_detail_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='first_name',
        ),
    ]
