# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-13 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('like_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='books',
            field=models.ManyToManyField(related_name='liked_books', to='like_books.User'),
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ManyToManyField(related_name='liked_users', to='like_books.User'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='upload_books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='like_books.Book'),
        ),
    ]
