# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-14 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('like_books', '0002_auto_20190213_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='upload_books',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='uploader',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='books',
            new_name='liked_users',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='like_books.User'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
