# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_user_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
